### ISSUE TITLE
Include bbox

### ISSUE THREAD

**Issue by stevage** [andrewharvey/geojson-polygon-labels#20]
It would be helpful to have an option:

```
--include-bbox Adds a _bbox property in the form [west, south, east, north].
```

**Comment by andrewharvey** [comment]
Hmm I'll need to think about this. On one hand I really like the unix philosophy of small programs which you can pipe together, and with that mindset you could do:

`cat geojson | geojson-bbox | geojson-polygon-labels`

using https://github.com/andrewharvey/geojson-bbox-cli

Are there advantages of having this built in instead of a pre-process?

**Comment by andrewharvey** [comment]
on the other hand I already include an option for area, so I guess including bbox makes it more complete.

**Comment by andrewharvey** [comment]
okay I'll accept a builtin `--include-bbox` option, it's not too much overhead. PRs welcome.

**Comment by stevage** [comment]
> Are there advantages of having this built in instead of a pre-process?

The big one being that a `--include-bbox` options would be discoverable, whereas your alternative solution was not known to me. One of the downsides of the Unix philosophy (which, personally I'm pretty skeptical of): you have to somehow know all of the possible tools that might be cobbled together to solve a particular problem. (And also hope they actually work together, have compatible formats, reasonable interfaces etc etc. In reality you end up with nightmares like xargs and sed ...).

FWIW, the particular motivation here is generating an index with a bbox which can be passed to mapbox-gl-js's `fitBounds` when a label is clicked on or selected from a list.

**Comment by andrewharvey** [comment]
It's a bit of a shame the GeoJSON bbox property https://tools.ietf.org/html/rfc7946#section-5 hasn't really taken off with client support. While I think it's cleaner to use

```js
{
  type: 'Feature',
  bbox: [...]
}
```

if you're loading your GeoJSON as a layer in GL JS, you wouldn't be able to access it.

**Comment by stevage** [comment]
Oh yeah, interesting point.
