### ISSUE TITLE
Add labels to tippecanoe

### ISSUE THREAD

**Issue by 2803media** [andrewharvey/geojson-polygon-labels#22]
Thanks for your tool, really helpful. 
I create a labels.geojson and then use tippecanoe to merge my labels.geojson and layer.geojson to build a mbtitles with 2 layers one labels and one layer.

I use vectorgrid protobuf to display the mbtitles in leaflet, I just missed the part how you display the labels, in tippecanoe I guess (don't know how to do that)? 

Thanks for your help

**Comment by andrewharvey** [comment]
Sorry I can't provide that kind of support here, maybe checkout http://gis.stackexchange.com/
