### ISSUE TITLE
How to achieve original label placement?

### ISSUE THREAD

**Issue by xeruf** [andrewharvey/geojson-polygon-labels#28]
explode:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/13354331/193892043-f1267095-8a1f-4c92-900f-f17e8aef3fd2.png">

combine:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/13354331/193892097-f266ac71-b613-4b13-bebd-6e4cb89dffcb.png">

neither matches the original label location exactly, can I achieve that? because I thought mapbox/polylabel is the original algorithm of the native OSM style?

**Comment by andrewharvey** [comment]
Looks like they are using PostGIS ST_PointOnSurface, I haven't looked into which algorithm they use.

**Comment by andrewharvey** [comment]
I recently added support for turf point on polygon, but it doesn't look like the same algorithm as ST_PointOnSurface, not sure if there's much we can do about this, so I'll close for now. If you have any suggestions please feel free to reopen.
