### ISSUE TITLE
Support newline-delimited geojson

### ISSUE THREAD

**Issue by stevage** [andrewharvey/geojson-polygon-labels#9]
Supporting [newline-delimited GeoJSON](http://geojson.win/newline-delimited/) would be a great and easy way of supporting processing huge files.

**Comment by andrewharvey** [comment]
Internally it's using https://github.com/mapbox/stream-features-from-file to stream features, and so far that's been working great with large input files.

That said, I'd be happy to accept a patch to support newline delimited GeoJSON.

**Comment by andrewharvey** [comment]
Actually I might swap from stream-features-from-file since it's heavy mapnik dependency can be hard to install, to https://github.com/node-geojson/geojson-stream which is what I used for https://github.com/andrewharvey/geojson-tippecanoe-extensions-from-attributes and seems to work great.

**Comment by stevage** [comment]
Hmm, `geojson-stream` is basically a wrapper around https://github.com/dominictarr/JSONStream/issues which has been archived now.
